### ISSUE TITLE
__set_name__ vs Iteration

### ISSUE THREAD

**Issue by cableray** [dhilst/delegate#4]
I was reading the documentation and noticed:

> At class parsing time is not possible for `DelegateTo` to know to what attribute you're assigning it to. For example `foo = DelegateTo('bar')` Pay attention that DelegateTo doesn't receive any information about `foo` attribute, but it will discover this latter. The method name is discovered at the first call. This is done by iterating over all the object's attributes. Once found the method is cached and no search is performed in the subsequent calls.

However, reading the python [descriptor docs](https://docs.python.org/3/howto/descriptor.html#automatic-name-notification) I noticed this:

> Sometimes it is desirable for a descriptor to know what class variable name it was assigned to. When a new class is created, the type metaclass scans the dictionary of the new class. If any of the entries are descriptors and if they define `__set_name__()`, that method is called with two arguments. The `owner` is the class where the descriptor is used, and the `name` is the class variable the descriptor was assigned to
> ...
> Since the update logic is in type.__new__(), notifications only take place at the time of class creation. If descriptors are added to the class afterwards, __set_name__() will need to be called manually.

So according to this, it seems like iteration is in fact not needed. Am I missing a reason it would be?

**Comment by dhilst** [comment]
In fact you're right, I didn't know of `__set_name__` at the time that I wrote this. I took a look on documentation and this is python >=3.6 feature, and tests are using 3.6 as the lower python version too, so I think we're safe to add this.

**Comment by dhilst** [comment]
I fixed it, thank you for taking time to report this. I will release a new version on pip soon 

Regards
