### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by egerlach** [dhilst/delegate#5]
Hi, noticed in #4 that you mentioned you would release a new version on PyPI. v1.6 is mentioned in `setup.py`, but isn't available on PyPI. Is it possible to get a release, and is there some way I can help?

**Comment by dhilst** [comment]
Hi @egerlach 

It's been a long time since I don't update this, yes, sorry about that. The library is a single .py file, I suggest you copy the source code to your codebase. The license is okay with that, and I'm okay with that, I'm archiving the repository
